### ISSUE TITLE
json output

### ISSUE THREAD

**Issue by epage** [rust-lang/testing-devex-team#1]
Tasks
- [x] rust-lang/rfcs#3558
- [x] Move https://github.com/epage/pytest-rs/ to rust-lang, see https://github.com/rust-lang/libtest-next
- [ ] Finish libtest-next experiment: https://github.com/rust-lang/libtest-next/milestone/1
- [ ] Upstream in libtest
- [ ] Experiment with `cargo test` ui on top of this
- [ ] Stabilize

**Comment by epage** [comment]
See also assert-rs/libtest2#42
