### ISSUE TITLE
custom test harness

### ISSUE THREAD

**Issue by epage** [rust-lang/testing-devex-team#2]
Summary of discussion with T-libs-api about providing a richer API in `test`:

> The biggest concern was with the compatibility surface that would have to be maintained and instead we went the opposite direction. Our aim is to make custom test harnesses first-class and shift the focus towards them rather than extending libtest. Hopefully, we can consolidate down on just a couple of frameworks with libtest providing us with the baseline API, reducing the chance that test writing between projects is too disjoint. I also hope we can share code between these projects to improve consistency and make it easier to conform to expectations.

See https://epage.github.io/blog/2023/06/iterating-on-test/

Tasks
- [ ] Vet all of the below with a reference implementation of a custom test harness: https://github.com/epage/pytest-rs/
- [ ] Opt-in to certain levels of `cargo test` / libtest interactions (rust-lang/cargo#15465)
- [ ] rust-lang/cargo#6945
- [ ] #3
- [ ] #6
- [ ] `main` from a dependency?  Might get this mostly for free by putting it in a prelude thanks for [1.79's](https://github.com/rust-lang/rust/releases/tag/1.79.0) [`imported_main`](https://github.com/rust-lang/rust/pull/122060/)
- [ ] #8
